### ISSUE TITLE
I only see the sidebar pane

### ISSUE THREAD

**Issue by Pierre-Thibault** [luccahuguet/yazelix#46] opened 2024-12-08 03:12 UTC
When I open a new tab in Wezterm, I see only one pane in Zellij called sidebar displaying Yazi. And when I choose a file in Yazi and type enter, the file opens in Helix in the same pane. Alt [ or Alt ] does nothing. What can I do to have the layout that you have?

**Comment by luccahuguet** [comment] 2024-12-22 21:21
this is the first time i've heard of this behavior

I would re-read the readme very carefully and try again if I were you

**Comment by luccahuguet** [comment] 2024-12-22 21:22
otherwise, we wait for someone with the same problem so we can identify what the cause is

**Comment by Pierre-Thibault** [comment] 2024-12-22 21:29
Sorry, it was not installed properly. Everything is fine now.

**Comment by luccahuguet** [comment] 2024-12-22 21:30
awesome! 

but thanks to your comment, I've updated the installing instructions

let me know if things are clearer now

**Comment by luccahuguet** [comment] 2024-12-22 21:31
i just copied the instructions from rustifier to this repo, to make it easier, nothing fancy

**Comment by luccahuguet** [comment] 2024-12-22 21:35
im closing this before I forget, but yah, let me know if the update is better

**Closed by luccahuguet** 2024-12-22 21:35 UTC
