### ISSUE TITLE
Failed to check if the command running in the current pane is helix

### ISSUE THREAD

**Issue by lens0021** [luccahuguet/yazelix#17] opened 2024-08-28 05:20 UTC
https://github.com/luccahuguet/yazelix/blob/8a675729a29e7678fe1770c36eb12ddcb44d3e16/yazi/open_file.sh#L10 is always false for me.

When I tested, `zellij action list-clients` is:
```
CLIENT_ID ZELLIJ_PANE_ID RUNNING_COMMAND
1         terminal_1     hx /some/path -w /some/path
```

so
```console
$ echo hx | grep -q "/hx$"; echo $?
1
$ echo hx | grep -q "hx$"; echo $?
0
```
for me.

* zellij 0.40.1
* grep (GNU grep) 3.11
* helix 24.7 (079f5442) installed using `dnf`
* Fedora Workstation

**Comment by luccahuguet** [comment] 2024-08-28 19:57
thanks, will look into it

**Comment by luccahuguet** [comment] 2024-08-28 19:57
did it fail all times or only some times?

**Comment by luccahuguet** [comment] 2024-08-28 20:11
was the helix pane next to the yazi pane? 

to the right of the yazi pane?

**Comment by lens0021** [comment] 2024-08-29 02:34
Hm, here are reproduction steps:

```
git clone --depth 1 https://github.com/luccahuguet/yazelix.git
cd yazelix
zellij --config-dir zellij options --layout-dir zellij/layouts
```

[Screencast from 2024-08-29 11-32-33.webm](https://github.com/user-attachments/assets/1ba7e7e0-23c2-4d5b-b55d-c692aa9988f6)

> did it fail all times or only some times?

sometimes it success, but I does not know when

**Comment by mohsini172** [comment] 2024-10-03 07:20
I had the same issue https://github.com/luccahuguet/yazelix/issues/18 
Didn't understand this issue before opening #18 so closed it now.

**Comment by lens0021** [comment] 2024-10-04 03:14
Today I cannot reproduce this by the mentioned method:
> ```
> git clone --depth 1 https://github.com/luccahuguet/yazelix.git
> cd yazelix
> zellij --config-dir zellij options --layout-dir zellij/layouts
> ```

I don't know what are differences

[Screencast from 2024-10-04 12-13-14.webm](https://github.com/user-attachments/assets/704ac3c0-9030-4326-a4b5-91b615be49ad)

**Comment by luccahuguet** [comment] 2024-10-04 20:43
> Today, I cannot reproduce this by the mentioned method:
> 
> > ```
> > git clone --depth 1 https://github.com/luccahuguet/yazelix.git
> > cd yazelix
> > zellij --config-dir zellij options --layout-dir zellij/layouts
> > ```
> 
>  Screencast.from.2024-10-04.12-13-14.webm 
> I don't know what are differences

This is good, I guess.

But nevertheless, I'll be switching the script from bash to nushell, and make it more sensible to detecting `hx` so it should fail much less

**Comment by luccahuguet** [comment] 2024-10-04 20:45
https://github.com/luccahuguet/yazelix/issues/20

**Comment by luccahuguet** [comment] 2024-10-05 21:25
presumably fixed by https://github.com/luccahuguet/yazelix/pull/21

will re-open if anyone can reproduce this on v4.1

**Comment by lens0021** [comment] 2024-10-06 00:56
Again happens.

[Screencast from 2024-10-06 09-47-09.webm](https://github.com/user-attachments/assets/fb1ae128-8f37-48fa-8110-6999a59b3a63)

Maybe it's because the machines I used are differences, but I am not sure.

In any case, I've found an issue on zellji's `list-clients` https://github.com/zellij-org/zellij/issues/3639
It will be good if using `zellij action dump-layout` instead, but its output is in [kdl](https://docs.rs/kdl/) format, and it seems there is no actively maintained kdl parsing CLI.

**Comment by luccahuguet** [comment] 2024-10-06 01:01
Thank you

i cannot reproduce, but will look into dump-layout...

**Comment by luccahuguet** [comment] 2024-10-06 01:02
can you try this again running nushell?

**Comment by lens0021** [comment] 2024-10-06 02:12
Changed the default shell to nushell by using `chsh` and logout, but same.

To debug, I've added next lines:

```nu
echo $"running_command: ($running_command)\n" | save --append ~/.config/yazelix/log
echo $"(zellij action list-clients)" | save --append ~/.config/yazelix/log
```

And this is the logs:
```
running_command: /home/nemo/.config/yazelix/yazi/open_file.nu
CLIENT_ID ZELLIJ_PANE_ID RUNNING_COMMAND
1         terminal_0     nu /home/nemo/.config/yazelix/yazi/open_file.nu /home/nemo/.config/yazelix/README.md
```

**Comment by lens0021** [comment] 2024-10-06 02:30
And `zellij action list-clients | detect columns` is `[{CLIENT_ID: 1, ZELLIJ_PANE_ID: terminal_0, RUNNING_COMMAND: nu, RUNNING_COMMAND: /home/nemo/.config/yazelix/yazi/open_file.nu}]`. I am not aware of nushell, so I don't know why the same keys exist in a list.

**Comment by luccahuguet** [comment] 2024-10-06 12:20
I see... funky business..

try this: 

```nushell
    let list_clients_output = (zellij action list-clients | lines | get 1)

    # Check if the command running in the current pane is hx
    if (is_hx_running $list_clients_output) {
```

if it works, I'll update the code

**Comment by lens0021** [comment] 2024-10-07 01:30
It perfectly works, thank you!

**Comment by luccahuguet** [comment] 2024-10-07 18:42
> It perfectly works, thank you!

awesome! I will further refine it before updating the code

hopefully I'll still count on your testing before committing the change

**Comment by luccahuguet** [comment] 2024-10-07 20:23
allright, i've commited some code to the main branch

should be working now

if it is, i will close this

**Comment by mohsini172** [comment] 2024-10-08 07:19
I will also test it out and will let you know.

**Comment by luccahuguet** [comment] 2024-10-15 13:45
> I will also test it out and will let you know.

Hello @mohsini172 , 

I am curious about whether the bug fix worked properly.. Did you get to try it?

**Comment by mohsini172** [comment] 2024-10-15 16:40
I just tested it with `nu` and now it works

**Comment by luccahuguet** [comment] 2024-10-15 18:09
> I just tested it with `nu` and now it works

Cool thanks, what about you @lens0021 ?

**Comment by lens0021** [comment] 2024-10-15 23:47
LGTM

**Comment by luccahuguet** [comment] 2024-10-16 18:43
> LGTM

Awesome! I am then closing this issue. 

This will be the last time I commit directly to main..

I will create contributing guidelines and add them to the readme

thanks for the help everyone

**Closed by luccahuguet** 2024-10-16 18:43 UTC
